-- session 1
SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;

-- session 2
START TRANSACTION;
UPDATE t SET c = "DIRTY" WHERE id = 1;

-- session 1
SELECT c FROM t WHERE id = 1;

-- session 2
ROLLBACK;