-- session 1
SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE;
START TRANSACTION;
SELECT c FROM t WHERE id = 1;

-- session 2
UPDATE t SET c = "Z" WHERE id = 1;

-- session 1
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;
