version: '3.8'

services:
  mariadb-server:
    container_name: mariadb-server
    image: mariadb:latest
    hostname: mariadb-server
    environment:
      MARIADB_ROOT_PASSWORD: RootPassword123!
      EDITOR: mcedit
    command: >
      /bin/bash -c "
        apt-get update &&
        apt-get install -y mc pspg &&
        docker-entrypoint.sh mariadbd
      "
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    restart: always

  code-server:
    container_name: code-server
    image: linuxserver/code-server:latest
    hostname: code-server
    ports:
      - "3333:8443"
    environment:
      - PASSWORD=CodePassword123!
      - DEFAULT_WORKSPACE=/home/workspace
    volumes:
      - ./../workspace:/home/workspace
      - ./extensions.sh:/etc/cont-init.d/99-extensions.sh
    restart: unless-stopped
